### ISSUE TITLE
Email Statistics: UI improvements

### ISSUE THREAD

**Issue by jowerner** [Xceptance/XCMailr#48]
* The Sender Domain tables lack a sorting indicator.
* The main heading has the same size and appearance as the sub headings.
* Change heading "Weekly" to "Last 7 Days", because that is what is shown.
* Adjust "Todays Sender Domains" and "Weeks Sender Domains" accordingly.
* The "Weekly" chart shows full days. Good or bad?
* The "Weekly" chart shows the count per hour while the "Last 24 Hours" chart shows the count per 15 min. This may cause confusion when comparing the two charts. Either unify this or add the range info to the series legend.

**Comment by marcuskaufmann** [comment]
* The Sender Domain tables lack a sorting indicator.
  * TODO
* The main heading has the same size and appearance as the sub headings.
  * done
* Change heading "Weekly" to "Last 7 Days", because that is what is shown.
  * done
* Adjust "Todays Sender Domains" and "Weeks Sender Domains" accordingly.
  * done
* The "Weekly" chart shows full days. Good or bad?
  * good in my opinion
* The "Weekly" chart shows the count per hour while the "Last 24 Hours" chart shows the count per 15 min. This may cause confusion when comparing the two charts. Either unify this or add the range info to the series legend.
  * TODO
