### ISSUE TITLE
Uppercase characters in mail result in "Some values are wrong or missing" message

### ISSUE THREAD

**Issue by wurzelkuchen** [Xceptance/XCMailr#53]
If you try to add an email address via the web interface and enter uppercase letters into the Name field, you'll get the message "Some values are wrong or missing" after pressing "Save".

Also the email is not added.  
This should either work or return a more specific message.

**Comment by pthum** [comment]
Note for the implementation:
I suppose that this issue should be split into two issues:
First: the regex on the address field in MBox.java is missing "A-Z" and thus does not match addresses with uppercase letters (which should be handled here).

Second (new issue): The validation handling in the whole application is very "rough" and only checks whether there are validation errors and throws this generic error message. At least this message (and the validation handling in every place) should be extended to  contain the fields with validation errors (but furthermore, from my nowadays perspective, the whole backend should be a REST(ful/like)-API which should return a json object containing the violated fields, so that the frontend can show the violated fields in a better way)

**Comment by h-arlt** [comment]
Fixed with #68
