### ISSUE TITLE
Emails sent to new manually created Email addresses aren't show under "My Emails"

### ISSUE THREAD

**Issue by ckeiner** [Xceptance/XCMailr#61]
While the forward function for new manually created Email addresses does work, neither these forwarded mails nor non-forwarded emails are shown in the tab "My Emails."
However, Email addresses created via the API retain the ability to show forwarded as well as non-forwarded email addresses.

**Comment by jowerner** [comment]
Looks like this is a negative side effect of caching the current user in memory for the current session. Since the user object also contains the current list of mailboxes, newly created mailboxes will be present in the database, but not in the cached user object. 

Workaround: When logging out and in again, the mails will be displayed as expected.

**Comment by jowerner** [comment]
In order to fix this issue, the current list of mailboxes is no longer taken from the cached user, but queried freshly from the database.
